#!/bin/sh


chown -R root:root /
chown -R sstic:sstic /home/sstic

mkdir /proc
mkdir /sys

mount -t proc proc /proc
mount -t sysfs sysfs /sys

chown root:root /proc
chown root:root /sys

chmod 700 /proc
chmod 700 /sys


insmod /lib/modules/sstic.ko
#mount -t devtmpfs none /dev
mknod /dev/ttyS0 c 4 64
mknod /dev/sstic c 248 0
chmod a+rw /dev/sstic

chmod o+rw /dev/ttyS0

chown -R sstic:sstic /home/sstic
chmod 700 /home/sstic
chmod 555 /home/sstic/service

stty erase ^H
#uncomment that for shell
#stty -F /dev/ttyS0 -icrnl -ixon -ixoff -opost -isig #-icanon -echo

#setsid cttyhack setuidgid 1000 sh
setuidgid 1000 /home/sstic/service

umount /proc
umount /sys

poweroff -f
